### ISSUE TITLE
API docs unclear

### ISSUE THREAD

**Issue by retorquere** [HiTask/api#2]
The API docs at https://github.com/HiTask/api state that the api URL is "https://hitask.com/api/{method} where {method} is the name of API method". At the same time, https://github.com/hitask/api/blob/master/documentation/user.md states "GET /user/authenticate will authenticate user using user name and password". However both https://hitask.com/api/user/authenticate and https://hitask.com/user/authenticate yield a 404 error when POSTed to.

**Comment by romanr** [comment]
@skyfrog Please update urls to include current API version

**Comment by skyfrog** [comment]
fixed
