### ISSUE TITLE
Please provide a simple example file...?

### ISSUE THREAD

**Issue by Anid4u2c** [HiTask/api#3]
I've used the HiTask web-based app for a while now and happy to find out that there is an API.

I'm researching some implementation solutions, so I created the following simple file to test the authentication process, but I can't even get myself authenticated - am wondering if you could revised the following code or provide a simple example script - specifically, regarding the hashed password.

This is my url scructure.
// For display purposes:  {'api_key' : apikey123 ; login : myusername; password : mypw;}
xmlhttp.open("GET","https://hitask.com/api/user/authenticate?api_key=apikey123&login=myusername&password=mypw",true);
 																		
Thanks,

- Nick

**Comment by skyfrog** [comment]
Hi Nick,

Currently it is possible to send password in plain text.
<code>
GET https://hitask.com/api/user/authenticate?api_key=yourapikey&login=yourusername&password=yourpassword
</code>

Best regards,
Vadim
