### ISSUE TITLE
Rate limit

### ISSUE THREAD

**Issue by JobaDiniz** [HiTask/api#4]
> We only allow a certain number of requests per client per minute. If you exceed this limit you will have to wait before your next request is processed.

How many request exactly?

**Comment by skyfrog** [comment]
@romanr please check limits

**Comment by romanr** [comment]
Rate limit is in range of tens of requests per minute. This is mainly to avoid abuse and DoS attacks. 
If you use API normally you don't have to worry about hitting the rate limit.
