### ISSUE TITLE
Edit tags of an item wrong docs

### ISSUE THREAD

**Issue by JobaDiniz** [HiTask/api#5]
In order to update tags of an item, the following JSON does not work:

```
{
"id": 7918155,
"tags": ["joba", "tag1"]
}
```

Documentation: https://github.com/HiTask/api/blob/master/documentation/item.md
> tags	array[string]	["work","home"]	array or tags added to item

Comma separated string **does work**: 
```
{
"id": 7918155,
"tags": "joba,tag1"
}
```

**Comment by skyfrog** [comment]
docs updated
